# A unique name for the cluster that this service node/instance belongs to; use alphanumeric and underscores only.
cluster: local_default

# Where does the system store information such as table definitions?
  systemTablePlacement: app_global:sys
# Define how yammer metrics should be pushed to third-party metrics aggregators/reporters
#metrics:
#  reporters:
#  - type: datadogExpansionFiltered
#    host: test-host
#    excludes:
#    - ch.qos.logback
#    - com.bazaarvoice.ostrich.pool
#    excludeExpansions:
#    - 5MinuteRate
#    - 15MinuteRate
#    - meanRate
#    - min
#    - max
#    - mean
#    - stddev
#    - p95
#    - p99
#    - p999
#    transport:
#      type: http
#      apiKey: invalid-key


dataCenter:
  # Which data center does this server belong to?
  currentDataCenter: datacenter1

  # What is the name of this DataCenter as configured in Cassandra's NetworkTopologyStrategy?
  cassandraDataCenter: datacenter1

  # All CREATE/DROP TABLE operations must occur in a single data center.  Which one is it?
  systemDataCenter: datacenter1

  # Load-balanced highly available base URL for the EmoDB service (ie. Amazon ELB base url).
  dataCenterServiceUri: http://localhost:7546

  # Load-balanced highly available base URL for the EmoDB administration tasks (ie. Amazon ELB base url).
  dataCenterAdminUri: http://localhost:7548

  # Load-balanced highly available base URL for the EmoDB system data center
  systemDataCenterServiceUri: http://localhost:7546


systemOfRecord:

  # How long should we retain historical deltas? To disable, use PT0S
  historyTtl: PT48H

  # All valid placement strings for create table operations.
  validTablePlacements:
  - "app_global:sys"
  - "app_global:default"
  - "app_remote:default"          # a dummy placement specific to a remote data center.  for testing only, not for practical use
  - "ugc_global:ugc"
  - "catalog_global:cat"

  # Minimum number of splits per table for newly created tables.  Higher numbers spread the data around the
  # Cassandra ring more evenly, but lower numbers require fewer get split operations to scan an entire table.
  minimumSplitsPerTable: 8

  # A per-keyspace map of Cassandra connection settings
  cassandraKeyspaces:
    app_global:
      cluster: emo_cluster
      clusterMetric: emo_cluster_metric_name
      keyspace: app_global
      dataCenter: datacenter1
      healthCheckColumnFamily: default_delta
      seeds: 127.0.0.1
      # zooKeeperServiceName: dev_sor_ugc_default-cassandra
      port: 9160
      maxConnectionsPerHost: 5
      latencyAware: true
      partitioner: bop
    ugc_global:
      cluster: emo_cluster
      clusterMetric: emo_cluster_metric_name
      keyspace: ugc_global
      dataCenter: datacenter1
      healthCheckColumnFamily: ugc_delta
      seeds: 127.0.0.1
      # zooKeeperServiceName: dev_sor_ugc_default-cassandra
      port: 9160
      maxConnectionsPerHost: 5
      latencyAware: true
      partitioner: bop
    catalog_global:
      cluster: emo_cluster
      clusterMetric: emo_cluster_metric_name
      keyspace: catalog_global
      dataCenter: datacenter1
      healthCheckColumnFamily: cat_delta
      seeds: 127.0.0.1
      # zooKeeperServiceName: dev_sor_cat_default-cassandra
      port: 9160
      maxConnectionsPerHost: 5
      latencyAware: true
      partitioner: bop

  slowQueryLog:
    tooManyDeltasThreshold: 20
    console:
      type: console


databus:
  # Cassandra connection settings
  cassandra:
    cluster: Databus Cluster
    keyspace: databus
    dataCenter: datacenter1
    healthCheckColumnFamily: subscription
    seeds: 127.0.0.1
    # zooKeeperServiceName: dev_datacenter1_databus_default-cassandra
    port: 9160
    maxConnectionsPerHost: 5
    latencyAware: true
    partitioner: bop


blobStore:

  # All valid placement strings for create table operations.
  validTablePlacements:
  - "media_global:ugc"
  - "media_global_mirror:media"
  - "blob_global:media"

  # source_placement: dest_placement
  placementsUnderMove:
    "media_global:ugc": media_global_mirror:media

  # Minimum number of splits per table for newly created tables.  Higher numbers spread the data around the
  # Cassandra ring more evenly, but lower numbers require fewer get split operations to scan an entire table.
  minimumSplitsPerTable: 8

  # A per-keyspace map of Cassandra connection settings
  cassandraKeyspaces:
    media_global:
      cluster: emo_cluster
      clusterMetric: emo_cluster_metric_name
      keyspace: media_global
      dataCenter: datacenter1
      healthCheckColumnFamily: ugc_blob
      seeds: 127.0.0.1
      # zooKeeperServiceName: dev_sor_ugc_default-cassandra
      port: 9160
      maxConnectionsPerHost: 5
      latencyAware: true
      partitioner: bop
    media_global_mirror:
      cluster: emo_cluster
      clusterMetric: emo_cluster_metric_name
      keyspace: media_global_mirror
      dataCenter: datacenter1
      healthCheckColumnFamily: media_blob
      seeds: 127.0.0.1
      # zooKeeperServiceName: dev_sor_ugc_default-cassandra
      port: 9160
      maxConnectionsPerHost: 5
      latencyAware: true
      partitioner: bop
    blob_global:
      cluster: emo_cluster
      clusterMetric: emo_cluster_metric_name
      keyspace: blob_global
      dataCenter: datacenter1
      healthCheckColumnFamily: media_blob
      seeds: 127.0.0.1
      # zooKeeperServiceName: dev_sor_ugc_default-cassandra
      port: 9160
      maxConnectionsPerHost: 5
      latencyAware: true
      partitioner: bop


queueService:
  # Cassandra connection settings
  cassandra:
    cluster: Databus Cluster
    keyspace: queue
    dataCenter: datacenter1
    healthCheckColumnFamily: manifest
    seeds: 127.0.0.1
    # zooKeeperServiceName: dev_datacenter1_databus_default-cassandra
    port: 9160
    maxConnectionsPerHost: 5
    latencyAware: true
    partitioner: bop


#jobs:

# Configure the ZooKeeper connection used for SOA service discovery
#zooKeeper:
  #namespace: datacenter1

  # ZooKeeper connection string that looks like "host:port,host:port,...".
  # It should include all members of the ZooKeeper ensemble.
  #connectString: localhost:2181

auth:
  # The admin and replication API keys must be encrypted using the encrypt-configuration-api-key command
  # The unencrypted values are included below to make local testing easier.  It should go without saying that
  # IN A PRODUCTION ENVIRONMENT DO NOT INCLUDE THE UNENCRYPTED KEYS IN THIS FILE!
  adminApiKey:       "zl+p3AU4/EgT8OtR0ZmLrkL70j0SklugAzd+xxYR1Dz/rioe5aXo4yay7sKi7PSKD59h7/HumH7442nGhlR2rw"  # local_admin
  replicationApiKey: "iuOPUIfI0lyxRrNZ9j9Aa68m1yrALBbVMw8kdqb6FVhSwMgOXVsuUblLr9nL73D4xpMVEZZHZr50pCBy1gbjDg"  # local_replication
  anonymousRoles:
  - anonymous

# Configure the HTTP server that listens for inbound requests
server:
  applicationConnectors:
    - type: instrumentedHttp
      port: 7546
  adminConnectors:
    - type: instrumentedHttp
      port: 7548

  gzip:
    # Most responses are small and not worth compressing.  Reduce CPU.
    enabled: false

    # If gzip is enabled, don't compress binary data types (ie. BlobStore input/output)
    compressedMimeTypes:
    - text/plain
    - text/html
    - text/xml
    - application/json
    - application/x.json-condition
    - application/x.json-delta

# Configure the HTTP client that EmoService uses to make outbound requests.
httpClient:
  # Timeout after 1 second while connecting.
  connectionTimeout: 1s

  # Timeout after 10 seconds while reading or writing.
  timeout: 10s

  # Keep connections open for 10 minutes.
  timeToLive: 10m

  # Don't track cookies.
  cookiesEnabled: false

  # Most responses are small and not worth compressing.  Reduce CPU.
  gzipEnabled: false
  gzipEnabledForRequests: false

  # Thread pool for JerseyClient's async requests.
  minThreads: 1
  maxThreads: 128

  # Re-use connections so we don't run out of ports if many requests are made in rapid succession.
  keepAlive: 2s


# Configure Logback logging
logging:
  level: INFO
  appenders:
    - type: console
      logFormat: "%-5p [%d{ISO8601,UTC}] [%thread] %c: %m%n%xEx"
  loggers:
    "org.apache.zookeeper": OFF
    "org.apache.curator": WARN
    "com.bazaarvoice.emodb.web.ddl.CassandraThriftFacade": WARN
